version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards/
    networks:
      - monitoring
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
    command:
      - '--path.rootfs=/host'
      - '--collector.systemd'
      - '--collector.processes'
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    volumes:
      - ./loki/config.yaml:/mnt/config/config.yaml
    ports:
      - "3100:3100"
    command:
      - "-config.file=/mnt/config/config.yaml"
    networks:
      - monitoring
    restart: always
  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./promtail/config.yaml:/mnt/config/config.yaml
      - /var/log/journal:/var/log/journal
    command:
      - "-config.file=/mnt/config/config.yaml"
    networks:
      - monitoring
    restart: always
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"
    networks:
      - monitoring
    restart: unless-stopped
  smtp:
    image: bytemark/smtp
    container_name: smtp
    environment:
      - RELAY_NETWORKS=*
      - RELAY_USERNAME=alertmanager
      - RELAY_PASSWORD=alertpass
    ports:
      - "1025:25"
    networks:
      - monitoring
    restart: unless-stopped


networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:
    name: grafana_data
  prometheus_data:
    name: prometheus_data