global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp:1025'
  smtp_from: 'gualtieri.hugo@hotmail.com'
  smtp_auth_username: "alertmanager"
  smtp_auth_password: "alertpass"
  smtp_require_tls: false

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'team']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default-alerts'
  routes:
    - matchers:
        - severity="critical"
      receiver: 'critical-alerts'

receivers:
  - name: 'default-alerts'
    email_configs:
      - to: 'gualtieri.hugo13@gmail.com'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'gualtieri.hugo13@gmail.com'
        send_resolved: true

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname, team, instance]